version: '3.1'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.2-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    ports:
      - 9864:9864
    networks:
      - hadoop
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.2-java8
    container_name: resourcemanager
    environment:
      - CLUSTER_NAME=test
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    ports:
      - 8088:8088
    networks:
      - hadoop
    depends_on:
      - namenode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.2-java8
    container_name: nodemanager
    environment:
      - CLUSTER_NAME=test
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    networks:
      - hadoop
    depends_on:
      - resourcemanager

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.2-java8
    container_name: historyserver
    environment:
      - CLUSTER_NAME=test
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    ports:
      - 8188:8188
    networks:
      - hadoop
    depends_on:
      - namenode
      - resourcemanager
      - nodemanager

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    environment:
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
      - HBASE_CONF_hbase_zookeeper_property_clientPort=2181
      - HBASE_CONF_hbase_rootdir=hdfs://namenode:9000/hbase
      - HBASE_CONF_zookeeper_session_timeout=60000
    ports:
      - 16010:16010
    networks:
      - hadoop
    depends_on:
      - zookeeper
      - namenode
      - datanode
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - hadoop
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_PORT=7077
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode
  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - 8081:8081
    networks:
      - hadoop
    depends_on:
      - spark-master
#  hive-metastore-postgresql:
#    image: postgres:10
#    container_name: hive-metastore-postgresql
#    environment:
#      - POSTGRES_DB=metastore
#      - POSTGRES_USER=hive
#      - POSTGRES_PASSWORD=hive
#    ports:
#      - 5432:5432
#    networks:
#      - hadoop
#
#  hive-metastore:
#    image: apache/hive:3.1.3
#    container_name: hive-metastore
#    environment:
#      - SERVICE_NAME=metastore
#      - DB_DRIVER=postgres
#      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore-postgresql:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive
#    ports:
#      - 9083:9083
#    volumes:
#      - ./hadoop-config:/opt/hive/conf
#      - ./warehouse:/opt/hive/data/warehouse
#    networks:
#      - hadoop
#    depends_on:
#      - hive-metastore-postgresql
#      - namenode
#      - datanode
#  hive-server:
#    image: apache/hive:3.1.3
#    container_name: hiveserver2
#    environment:
#      - SERVICE_NAME=hiveserver2
#      - IS_RESUME=true
#      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://hive-metastore:9083
#    volumes:
#      - ./hadoop-config:/opt/hive/conf
#    ports:
#      - 10000:10000
#      - 10002:10002
#    networks:
#      - hadoop
#    depends_on:
#      - hive-metastore
#      - namenode
#      - datanode

networks:
  hadoop:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
