spring:
  application:
    name: mj-admin
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: false
    deployment-mode: never-fail
    process-definition-location-prefix: classpath:/process/
    async-executor-activate: false