admin:
  token:
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: false
    # token过期时间（分钟）
    tokenExpireTime: 360
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 3
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  cache:
    # 缓存时间单位：day、hour、minute
    timeUnit: hour
    # 时间
    time: 8